# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build, Test, and Deploy Python App to Azure Web App - TweetSentimentAnalysisECO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest
        env:
          PYTHONPATH: ${{ github.workspace }}  # Ajoute le chemin racine au PYTHONPATH pour éviter les problèmes d'importation

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ce job ne s'exécutera que si "build-and-test" réussit
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Requis pour demander un JWT

    steps:
      - name: Download artifact from build-and-test job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D84BD4E90094FF5987D5831A2ADEB23 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AFECED4504D64E9680A288FCE216CEF8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_76381FE1A4E9453995396052CFFC3D97 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TweetSentimentAnalysisECO'
          slot-name: 'Production'
